### ISSUE TITLE
请问一下如何修改使方向键上和方向键下恢复原来翻页的功能

### ISSUE THREAD

**Issue by xyyuhans** [Aoerz/UserScripts#1]
脚本很好用，不过我想用方向键上和方向键下翻页，因为不想再用鼠标滚轮了。。。
- 尝试1
我没接触过脚本，粗糙地看了一下脚本。尝试把 `case 38 68 83 40`删掉，因为这实现调节音量功能，应该和方向键上下有关。结果方向键上下既不能调节音量，也不能翻页。原因应该是脚本会把键盘的功能覆盖掉。
- 疑问
应该把 `case 38 68 83 40`里的内容改成方向键的功能就可以了，不过新手表示无从下手，希望能够指点一下。
Thank you for your time.

**Comment by yu-dou** [comment]
你把  `event.preventDefault();` 删了，不过可能会带来副作用。
[event.preventDefault](https://developer.mozilla.org/zh-CN/docs/Web/API/Event/preventDefault)

ps:这脚本我当时看网课随手涂的，我也不懂js.

**Comment by xyyuhans** [comment]
感谢，成功了，只是按 `space` 的时候，既会暂停，又会往下滚动，貌似默认快捷键和脚本同时起作用了，修改一下暂停的键位就可以了。
